
import {
  LayoutDashboard,
  Users,
  CalendarDays,
  Stethoscope,
  FlaskConical,
  Settings,
  LogIn,
  UserPlus,
  ChevronDown,
  ChevronRight,
  Search,
  PlusCircle,
  MoreHorizontal,
  FileText,
  Edit,
  Trash2,
  Filter,
  Eye,
  CalendarPlus,
  Clock,
  Bot,
  Moon,
  Sun,
  LogOut,
  BriefcaseMedical,
  AlertTriangle,
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Patients: Users,
  Appointments: CalendarDays,
  Doctors: Stethoscope,
  Optimizer: Bot,
  Settings: Settings,
  Login: LogIn,
  UserPlus: UserPlus, // Corrected: Was Signup: UserPlus
  Signup: UserPlus, // Keep Signup as an alias if needed, or remove if UserPlus is preferred everywhere
  Logout: LogOut,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  Search: Search,
  PlusCircle: PlusCircle,
  MoreHorizontal: MoreHorizontal,
  FileText: FileText,
  Edit: Edit,
  Trash2: Trash2,
  Filter: Filter,
  View: Eye,
  CalendarPlus: CalendarPlus,
  Clock: Clock,
  Bot: Bot, // Alias for Optimizer
  Moon: Moon,
  Sun: Sun,
  Logo: BriefcaseMedical,
  AlertTriangle: AlertTriangle,
};

export type IconName = keyof typeof Icons;
